# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RMLStar' do
  pod 'RMLStar', :path => "../"
end

target 'RMLStarTests' do
  pod 'RMLStar', :path => "../"
end

