# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.4'
use_frameworks!

target 'RMLStarReceiptPrinter' do
  pod 'RMLStarReceiptPrinter', :path => "../"
end

target 'RMLStarReceiptPrinterTests' do
  pod 'RMLStarReceiptPrinter', :path => "../"
end

